### ISSUE TITLE
Benchmarking : How to use multi-cpu for l1-wavelet recon

### ISSUE THREAD

**Issue by valeryozenne** [mikgroup/sigpy#47]
Hi,

Thanks for making Sigpy available. I would like to use and benchmark Sigpy. I'm not yet familiar with it, I might have missed something. 

Installation (and tutorial) run smootly using pip for the libraries and using the command python3 setup.py install. I'm using a laptop on Ubuntu 18.04 with 
- Intel® Core™ i7-4910MQ CPU @ 2.90GHz × 8
- Nvidia Quadro 4Go 
- 32 Go Ram.

I didn't succeed to use/activate multi-cpu usage for performing operation either IFFT and coil map estimation or the L1WaveletRecon.  For instance, EspiritCalib never finished while JsenseRecon was actually running on but one cpu as well as the L1WaveletRecon. Do you have any example to follow ?

The code is here in case: https://github.com/valeryozenne/sigpy-3D-ifft-cms/blob/master/main.py

Thanks in advance,
Valéry

**Comment by frankong** [comment]
SigPy by default only uses one CPU. To use multi-CPU, you'll need to use MPI with [sigpy.Communicator](https://sigpy.readthedocs.io/en/latest/generated/sigpy.Communicator.html#sigpy.Communicator).

There isn't a demo for it right now, but I'm willing to help. To start, you'll need to install MPI and `mpi4py`. Then to launch your script with say 8 CPUs, you can do:
`mpiexec -n 8 python main.py`

Your script will be launched 8 times with different threads. Inside your code, you'll need to create a Communicator object. You can then use the communicator object to split and combine results between threads.

**Comment by valeryozenne** [comment]
Thanks for the answer. Just some thoughts below:

I guess this is not straightforward. Splitting the data need to be done carefully, depending the operation I'm doing, it might be difficult to split matrix along the encoding and channel dimension. It will work only if I have independent datasets (like 2D multi-slice) but what is the preferable way if want to reconstruct one dataset with regularization on subsampled dimension: [kx, ky, kz, cha, contrast] ?

I would like to have your opinion, if we consider a 5D dataset with random acceleration along ky and kz and multiple contrasts. Do you think that it is possible to split the data along the readout direction (fully sampled) for non linear reconstruction? I know it is possible for standard 3D GRAPPA as the kernel application is the same in every location but here I'm not really sure. 

If you have any example regarding the communicator object I will be interested to use it. This might be particularly usefull for optimizing parameters as the reconstruction time seems relatively long on one CPU.   

Thanks in advance,
Valéry

**Comment by sidward** [comment]
Hi,

As long as there is no correlation between the readout and phase encodes (like with wave for example), you should be able to process the data slice by slice after taking the inverse Fourier transform along the readout direction.

**Comment by valeryozenne** [comment]
Nice, basically, if I can split the data along the readout direction, I might also be able to do the operation slice by slice also in the GPU device where memory size is generally too small for large datasets. It will depend from which point I can split the data. 

Just to be 100% sure, if I go back to the demo 03-building-an-l1-wavelet-recon-app.ipynb with a 5D dataset [kx, ky, kz, cha, contrast], dividing a 256 readout into blocks of 32 , and doing the L1Wavelet reco on the block of readout (32 voxels, ky, kz, cha, contrast) will result in the same result ? 

For my understanding , coil sensitivity map and wavelet are related to spatial information so splitting the data could result in different values. Assuming the size of block of readout is larger that the actual kernel operation inside the functions (a spatial derivative for instance), it could work. Do you confirm my thought.   

Do you have any articles to refer  / demo that my help me to understand why it is working?
Thanks in advance,
Valéry

**Comment by sidward** [comment]
Hi,

If you ignore the wavelet penality, in principle, solving the least squares problem slice-by-slice, or block-by-block, should result in the same answer. You are correct in that applying a 3D regularizer will result in slightly different solutions based on how you partition your data. I would personally expect better wavelet sparsity the larger the readout block, but I would test this.

That being said, in my experience, most of the computational burden comes from the least squares (or data consistency) term. If A is your forward operator, I would recommend that you use the ```ToDevice``` Linop along with the ```Diag```, ```Hstack``` and ```Vstack``` to break a large problem into smaller ones so that Ax, AHx and AHA that can be processed on the GPU.  For most kinds of problems in MRI, this ```ToDevice``` trick will work directly for the coil dimension.  I would also recommend looking into the communicator object, as described by Frank, to use multiple CPUs in a similar manner.

Likewise, if you would like to use a full volume wavelet transform and it does not fit on the GPU, you can process it on the CPU while still taking advantage of the GPU for the data-consistency term.

Note that there will be some penalty to moving data around.

For an example of splitting multi-contrast data to perform non-linear reconstruction, please take a look at the following. An example reconstruction pipeline is discussed in-depth.

https://arxiv.org/pdf/1809.04195.pdf

Hope this helps!

**Comment by valeryozenne** [comment]
Yes, it helps a lot. Thanks. 
I close the issue.
